<?php
/**
 * InlineResponse2002Test
 *
 * PHP version 5
 *
 * @category Class
 * @package  daxslab\enzona\qr
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * QRAPI
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.8
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace daxslab\enzona\qr;

/**
 * InlineResponse2002Test Class Doc Comment
 *
 * @category    Class
 * @description InlineResponse2002
 * @package     daxslab\enzona\qr
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class InlineResponse2002Test extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "InlineResponse2002"
     */
    public function testInlineResponse2002()
    {
    }

    /**
     * Test attribute "vendor_identity_code"
     */
    public function testPropertyVendorIdentityCode()
    {
    }

    /**
     * Test attribute "create_at"
     */
    public function testPropertyCreateAt()
    {
    }

    /**
     * Test attribute "update_at"
     */
    public function testPropertyUpdateAt()
    {
    }

    /**
     * Test attribute "image"
     */
    public function testPropertyImage()
    {
    }
}
